site_name: Metabuli - Sensitive and Specific Taxonomic Classification
site_description: Sensitive and specific metagenomic classification via joint analysis of amino acid and DNA
site_url: https://jaebeom-kim.github.io/metabuli-doc/
repo_url: https://github.com/steineggerlab/Metabuli
repo_name: steineggerlab/Metabuli

theme:
  name: material
  logo: assets/marv_metabuli.png
  favicon: assets/marv_metabuli.png
  palette:
    - scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - md_in_html

nav:
  - Introduction:
      - Metabuli: index.md
      - Improvements: introduction/improvements.md
      - Update Log: introduction/updates.md
  - Metabuli App: 
      - Introduction: metabuli-app/metabuli-app.md
      - Raw-read QC: metabuli-app/qc.md
      - Classification: metabuli-app/classification.md
      - Database curation: metabuli-app/db.md
  - Modules:
      - Overview: modules/index.md
      - classify: modules/classify.md
      - refine-results: modules/refine-results.md
      - extract: modules/extract.md
      - build: modules/build.md
      - updateDB: modules/update-db.md
  - Databases:
      - New Databases: databases/new-database.md
      - Old Databases: databases/old-database.md
  - Utilities:
      - Bracken: util/Bracken.md
  - Example: example.md

extra_css:
  - stylesheets/extra.css